# frontend/Dockerfile.dev

# Build stage: use Node.js image to build the frontend app
FROM node:23-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage: use Nginx to serve the built static files
FROM nginx:1.29.1-alpine3.22-slim
COPY --from=builder /app/dist /usr/share/nginx/html   
COPY nginx.conf /etc/nginx/conf.d/default.conf        
EXPOSE 80                                             
CMD ["nginx", "-g", "daemon off;"]                    

