


# Dcokerfile.NodeJS

FROM node:23-slim

# Create app directory
WORKDIR /login/login

# Copy package files before installing dependencies
COPY login/package*.json ./

# Install dependencies (omit dev dependencies for production)
RUN npm install --omit=dev

# Copy the rest of the application code
COPY . .

# Expose the port
EXPOSE 5000

# Run the app
# CMD ["npm", "start"]
CMD ["node", "server.js"]
