name: CI/CD Pipeline - Deploy to Localhost

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to main

jobs:
  deploy:
    runs-on: self-hosted  # Uses the self-hosted runner (your local machine)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Run Containers
        run: |
          docker-compose down
          docker-compose up --build -d

      - name: Verify Deployment
        run: curl -f http://localhost:8008/docs || exit 1
